import "../../public/styles/main/main.css"
import { Poppins } from "next/font/google";


const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "800"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
